server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/employee/v3/api-docs, /employee/**
        - id: consumer-service
          uri: http://localhost:8082
          predicates:
            - Path=/consumer/v3/api-docs, /consumer/**

springdoc:
  enable-native-support: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /employee/v3/api-docs
        name: api-employee
      - url: /consumer/v3/api-docs
        name: api-consumer
